### ISSUE TITLE
support binary files

### ISSUE THREAD

**Issue by eighthave** [jedisct1/ipgrep#3]
Python 2 is dead!  Long live Python 3!  And it would be great to include _ipgrep_ there too

**Comment by jedisct1** [comment]
Pull request welcome 😀

**Comment by eighthave** [comment]
OK, I'm game.  Any insights into why this happens:
```console
$ find /home/hans/code/at.or.at/plugoffairplane/ -type f|xargs cat | python3 ./ipgrep.py 
Traceback (most recent call last):
  File "./ipgrep.py", line 116, in <module>
    for line in fileinput.input():
  File "/usr/lib/python3.7/fileinput.py", line 252, in __next__
    line = self._readline()
  File "/usr/lib/python3.7/fileinput.py", line 366, in _readline
    return self._readline()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 420: invalid continuation byte
```

**Comment by eighthave** [comment]
turns out this is a binary vs string issue, not a python 2 vs 3 issue.  I changed all the regexs to `b''` strings, would that work for you?

**Comment by eighthave** [comment]
Ok, its working!  I'm running this on a collection of many thousands of Android APKs.  I'll create a merge request once it completes successfully.

**Comment by jedisct1** [comment]
Looking good, thanks!
